### ISSUE TITLE
Redirecting incorrect sub-routes to notFound

### ISSUE THREAD

**Issue by nareshbhatia** [nareshbhatia/mobx-state-router#1]
Suppose we have a route pattern like `/departments/:id` and there are only two valid values for `:id`. If we get an invalid value for `:id`, what's the best way to send the router to the `notFound` state?

**Comment by lucianlature** [comment]
The best way is the React Router's approach on this, IMHO.

It uses the `Switch` component, which only renders the first matched component:

```
<Switch>
      <Route exact path="/" component={App}/>
      <Route path='/departments' component={DepartmentsComponent}>
        <Route path='departments/:id' component={DepartmentComponent} />
        <Route path='*' component={DepartmentNotFound} />
    </Route>
     <Route path="*" component={NotFound}/>
</Switch>
```

In this case, I think we should just use the `beforeEnter` hook to check if the `id` is valid. If not, simply change the state of the Route to `notFound`.

**Comment by carlosagsmendes** [comment]
@lucianlature but that wouldn't work in this case since there is no concept of sub-routes right?

I'm taking a look at different routers. Vue's router [approach to nested routes](https://router.vuejs.org/en/essentials/nested-routes.html) is also great.

@nareshbhatia would you be open to add nested routes and [named views](https://router.vuejs.org/en/essentials/named-views.html) to the project? We would be glad to contribute.

**Comment by lucianlature** [comment]
@carlosagsmendes That's correct.

**Comment by nareshbhatia** [comment]
@carlosagsmendes, while there are no nested routes in mobx-state-router, I think @lucianlature suggests a good solution. `beforeEnter` should work perfectly for this. I am closing this issue.

As for nested routes:

1. I would like to first understand the need for it. Is there a use case that is simply not possible without it? Even your master/detail use case was easily implemented with a single RouterView.
2. We need to weigh in the complexity of introducing nested routing. I like Steve Job's advice on this: [Simple can be harder than complex](https://www.goodreads.com/quotes/445279-simple-can-be-harder-than-complex-you-have-to-work).

I will surely go through the links you have listed above. If we need to pursue this route, let's open a new issue to discuss.
