### ISSUE TITLE
Question: May it works with react native?

### ISSUE THREAD

**Issue by TIMNHE** [nareshbhatia/mobx-state-router#10]
I'm going to start a new project with react native and I'm looking for router alternatives, so ... 
is mobx-state-router working well with react-native?

**Comment by nareshbhatia** [comment]
While I haven't tried it with React Native, I don't see any reason why it shouldn't work. Since React Native apps do not have a browser address bar, drop the `HistoryAdapter` altogether. Just use the `RouterStore` and the `RouterView` - should work fine. Let me know how it works for you!
