### ISSUE TITLE
Error when MobX strict-mode is enabled

### ISSUE THREAD

**Issue by ARMEGO** [nareshbhatia/mobx-state-router#110]
After adding MobX strict-mode configuration as mentioned in [this configuration](https://mobx.js.org/configuration.html#linting-options) an error is thrown in the UI as under:

`Unhandled Rejection (Error): [mobx] Since strict-mode is enabled, changing observed observable values outside actions is not allowed. Please wrap the code in an `action` if this change is intended. Tried to modify: RouterStore@1.isTransitioning`

**Comment by nareshbhatia** [comment]
Which version of mobx-state-router are you using? Have you tried this with version 6.0.0-beta.1?

**Comment by armego-philips** [comment]
I'm using version "^4.0.6". No, I haven't tried the beta version.

**Comment by ARMEGO** [comment]
This particular issue is fixed in version 6. Thanks.
