### ISSUE TITLE
code splitting : splitting of stores and other related components files - 

### ISSUE THREAD

**Issue by mnshgautam** [nareshbhatia/mobx-state-router#118]
is there any support for code splitting using web pack plugin, based on routes, something similar to what react router supports `https://reactrouter.com/web/guides/code-splitting` @nareshbhatia

**Comment by nareshbhatia** [comment]
Hi @mnshgautam, haven't given this a thought. What we have is an example of lazy loading based on pages. Please see https://github.com/nareshbhatia/mobx-state-router/tree/mobx6-update/examples/suspense-lazy-loading.
