### ISSUE TITLE
inconvenient use of the Link

### ISSUE THREAD

**Issue by xFloooo** [nareshbhatia/mobx-state-router#13]
Every time we need to do 2 things

1. extract and transmit `routerStore`
2. generate and transmit `new RouterState(...)`

the `<Link />` itself can do this if it has a `routerStore`

my suggestion: add a `routerStore` to the react context in the `RouterView` component.
Then api `<Link />` will become simple...

```jsx
const linkParams = {
    routName: ...,
    params: ...,        // may be absent
    queryParams: ...    // may be absent
}

<Link params={linkParams}>referenceText</Link>
```

**Comment by xFloooo** [comment]
It would be nice to put class="active" if the link is the same as url.
or make it as in a `react-router` ->  [NavLink](https://reacttraining.com/react-router/web/api/NavLink)

**Comment by nareshbhatia** [comment]
Done.

Added `<RouterLink>` which allows the simpler API suggested by you and also `className` and `activeClassName` properties.

Please see example in [mobx-shop](https://github.com/nareshbhatia/mobx-shop/blob/master/src/features/signin/signin-page.js#L85-L87) and let me know if this works for you.

**Comment by xFloooo** [comment]
@nareshbhatia Excellent!
Translated [boilerplate](https://github.com/xFloooo/mobx-state-router-ssr-boilerplate/commit/02f9ae72eee99e577022ece8a7de1d783d27af5c#diff-b9fabfacdfc52a92e2a5f4ee89aa8c43L36) version 3.0 - everything works great

**Comment by nareshbhatia** [comment]
Good to know!
