### ISSUE TITLE
default route settings

### ISSUE THREAD

**Issue by xFloooo** [nareshbhatia/mobx-state-router#20]
for example we have rout  `/:user`, and by default we would like to see `user=guest`, but you do not need to write `guest` in the browser line.
Or make a nesting with `middleware`

**Comment by BANOnotIT** [comment]
@xFloooo doesn't work construction like?
```js
'user': '/:user',
'users': '/'
```

ps. If it doesn't, I'll look for another router)

**Comment by xFloooo** [comment]
@BANOnotIT your requirement is working, my question about another...

**Comment by nareshbhatia** [comment]
This one has been long open. Giving it a little thought, if `user=guest` is the default, then the url typed in the browser would be `/`. This could be confused with a real route `/` - don't want to take this chance. Closing.
