### ISSUE TITLE
only initial route transition hooks are not invoked, not thrown ones

### ISSUE THREAD

**Issue by jzimmek** [nareshbhatia/mobx-state-router#29]
lets assume we have 2 routes X and Y.

Y needs some initialization in before/onEnter to work properly. X will throw RouterState("Y") under some conditions.

but throwing a RouterState("Y")  does not tigger the transition hooks of "Y" at all.

i am not sure if this is a bug or defined behavior.

**Comment by kutuluk** [comment]
[![Edit z6pmjwrpq4](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/z6pmjwrpq4)

see console. all triggers are invoked

**Comment by nareshbhatia** [comment]
@jzimmek, does this answer your question? If yes, please close this issue.

**Comment by nareshbhatia** [comment]
Closed due to inactivity.
