### ISSUE TITLE
ViewMap item type: React.Component vs React.ReactNode

### ISSUE THREAD

**Issue by kutuluk** [nareshbhatia/mobx-state-router#31]
Inconsistency of documentation with code:

README.md:
>```ts
>export interface ViewMap {
>    [routeName: string]: React.Component;
>}
>```

actually: [router-view.tsx](https://github.com/nareshbhatia/mobx-state-router/blob/master/src/components/router-view.tsx#L5-L7)

>```ts
>export interface ViewMap {
>    [routeName: string]: React.ReactNode;
>}
>```

I believe that React.Component is better than React.ReactNode and it is necessary to bring the code into compliance with the documentation.

**Comment by kutuluk** [comment]
Moreover, I suggest generally get rid of the viewMap property in RouterView and add instead the component property in Route. Because in fact in the current implementation there is a rigid binding of the router to the component, only it is done in a strange and unnatural way by means of a separate map.

**Comment by kutuluk** [comment]
Then the RouterView will be:

```jsx
@observer
export class RouterView extends React.Component<RouterViewProps, {}> {
    render() {
        const {
            routerStore: { routerState }
        } = this.props;

        if (process.env.NODE_ENV === 'development') {
            console.log(`RouterView.render() - ${JSON.stringify(routerState)}`);
        }

        const { routeName, ...props } = routerState;
        const { component: View } = routerStore.getRoute(routeName);

        return View ? <View {...props} /> : null;
    }
}
```

**Comment by kutuluk** [comment]
You can do more universally:

```jsx
@observer
export class RouterView extends React.Component<RouterViewProps, {}> {
    render() {
        const { routerStore, viewMap } = this.props;
        const { routerState } = routerStore;

        if (process.env.NODE_ENV === 'development') {
            console.log(`RouterView.render() - ${JSON.stringify(routerState)}`);
        }

        const { routeName, ...props } = routerState;

        const View = viewMap
            ? viewMap[routerState.routeName]
            : routerStore.getRoute(routeName).component;

        return View ? <View {...props} /> : null;
        // or
        // return View ? <View routerState={routerState} /> : null;
    }
}
```

Then, when specifying the `viewMap`, the components will be taken from it. Otherwise, from the `route.component`.

**Comment by kutuluk** [comment]
You can go even further. Add the `stories` property to the route and send them to components, removing the need to inject them directly to each component:

```jsx
export interface Route {
    ...
    component: React.Component,
    stories: string[],
}

@observer
export class RouterView extends React.Component<RouterViewProps, {}> {
    render() {
        const { routerStore, viewMap } = this.props;
        const { routerState } = routerStore;

        if (process.env.NODE_ENV === 'development') {
            console.log(`RouterView.render() - ${JSON.stringify(routerState)}`);
        }

        const { routeName, ...props } = routerState;

        const { component, stories } = routerStore.getRoute(routeName);

        const View = viewMap
            ? viewMap[routerState.routeName]
            : component;

        const storiesProp = {};
        stories.foreach(store => storiesProp[store] = routerStore.rootStore[store]);

        return View ? <View {...props} stories={storiesProp}/> : null;
        // or
        // return View ? <View routerState={routerState} stories={storiesProp} /> : null;
    }
}
```

**Comment by nareshbhatia** [comment]
Hi @kutuluk, there was an issue earlier when a `routeName` was associated with a `React.Component`. TypeScript did not like it in some use cases (I can't remember which). I had to relax the type to `React.ReactNode` to make it work. Here's the related commit: https://github.com/nareshbhatia/mobx-state-router/commit/e0d9dd499f8c98991de219c74a67ab0d7492960e. I have fixed the documentation to match the code.

As far as your suggestion regarding removing `viewMap` from `RouterView` and adding a `component` property to `Route`, I don't quite agree. The whole idea behind the `RouterStore` is complete separation of UI from state. If we introduce the idea of components in the core router, then the router becomes dependent on the UI. We can no longer think of the router as a pure JavaScript state machine!

If I have misunderstood your suggestion, please feel fee to clarify.
