### ISSUE TITLE
Add v.4 branch to repository and @4.0.0-beta tag to npm

### ISSUE THREAD

**Issue by kutuluk** [nareshbhatia/mobx-state-router#33]
This will allow to safely make breaking changes and test in a production-like environment.

**Comment by nareshbhatia** [comment]
Unfortunately, it is not clear to me how to publish multiple releases to npm using [semantic-release](https://github.com/semantic-release/semantic-release). This feature is under discussion in their issue list - see https://github.com/semantic-release/semantic-release/issues/563.

I suggest handling breaking changes as follows:
- Create a feature branch with an appropriate name
- Write tests to make sure the feature works
- Package a local version of mobx-state-router: `npm pack`. This will create a package called `mobx-state-router-0.0.0-development.tgz` in your local repo.
- Install this package in your target application to test the feature.

I know this is a bit more tedious, but I don't know of an easier way right now. Suggestions welcome.
