### ISSUE TITLE
Wait for initialization

### ISSUE THREAD

**Issue by yacut** [nareshbhatia/mobx-state-router#34]
Hallo.

Unfortunately  I could not find information on this issue.

_For example:_
App saves the auth data in cookie after login. 
When user reload the page it should check that credentials are valid and only when start to route or fetch data etc. 

@nareshbhatia Do you have some solution for this case?

**Comment by nareshbhatia** [comment]
This is a minor extension of the use case that is implemented in [mobx-shop](https://github.com/nareshbhatia/mobx-shop/blob/master/src/shared/stores/auth.store.js). Basically you need to save the auth data in the AuthStore and simultaneously in the cookie (or localStorage). When the page is reloaded, the app should initialize the AuthStore with the data in the cookie. This should happen in [app.js](https://github.com/nareshbhatia/mobx-shop/blob/master/src/app.js), before any view is rendered. From this point on the router should redirect to the correct page that is requested in the URL (it should not care whether the auth data came from the cookie).

Read this section in the docs for the overall workflow: https://github.com/nareshbhatia/mobx-state-router#redirecting-to-the-sign-in-page
