### ISSUE TITLE
Adding routes dynamically

### ISSUE THREAD

**Issue by gcazaciuc** [nareshbhatia/mobx-state-router#35]
Hi,

We have a situation where the list of routes isn't known upfront but it needs to be constructed dynamically. 
Is there a way to add routes definitions dynamically ?

Thanks!

**Comment by nareshbhatia** [comment]
Hi @gcazaciuc, there is no API for adding routes dynamically. However, you could access `RouterStore.routes` directly and update them dynamically. This is not a use case that I designed the router for, so your milage may vary!

The only way in which the constructor changes the `routes` array is to add an initial route to it. See [here](https://github.com/nareshbhatia/mobx-state-router/blob/master/src/router-store.ts#L90).

I am curious what your actual use case is. Why do you need to update routes dynamically.

**Comment by gcazaciuc** [comment]
I have multiple React applications on the same page( there is a legacy system in which parts of the page are being gradually replaced  by React components implementing different flows).
I would like each React application to have access to the same Router instance and add their routes to it.
Otherwise, if they are separated, whenever the URL changes one of the React app will enter the not found route. Hope it makes sense.

**Comment by nareshbhatia** [comment]
@gcazaciuc, interesting use case! Hopefully you will be able to utilize my suggestion above. Closing for now.
