### ISSUE TITLE
Lazy evaluate the transition hook

### ISSUE THREAD

**Issue by bitttttten** [nareshbhatia/mobx-state-router#36]
Is there a way to lazyily evaluate a transition hook?

For example on client, I would like the app to render lazily so the user experience is cleaner. It would show preloading states of components or the route, and then fill in the data when completed. On the server however, I want to wait for the transition hook to finish so I have all my data before sending it down so that I do not send down preloading states.

For example I would imagine I want would change the transition hook chain to the below code on client, and leaving it as it is on the server.

```
([beforeExit, beforeEnter, onExit, onEnter]
  .reduce(function (promise, hook) {
            return hook
                //  ? promise.then(function () { return hook(fromState, toState, _this); })
                ? promise.then(function () { hook(fromState, toState, _this); return Promise.resolve(); })
                : promise;
        }, Promise.resolve())
```

Where a transition hook would be something like the following:

```
		onEnter: (fromState, toState, routerStore) => {
			const { rootStore: { articlesStore } } = routerStore
			return articlesStore.fetchArticles()
		},
```

Perhaps this problem is solved another way, but I would love to know if this idea is possible.

**Comment by nareshbhatia** [comment]
If I understand you correctly, the way to lazily evaluate a transition hook, is to resolve it immediately inside the router. However wait for the async fetch to finish in your target store. So in your example, the `onEnter` hook will look like this (for the client use case):

```
onEnter: (fromState, toState, routerStore) => {
    const { rootStore: { articlesStore } } = routerStore;
    articlesStore.fetchArticles();
    return Promise.resolve();
},
```

This will make sure that your target view is loaded right away, however it will populate with data only when the fetch returns.

Your articleStore will need to keep track of the loading state. Something like this:

```
export class ArticlesStore {
    rootStore;
    @observable isLoading = true;
    @observable articles;

    @action
    startLoading() {
        this.isLoading = true;
    }

    @action
    setArticles(articles) {
        this.articles = articles;
        this.isLoading = false;
    }

    @action
    fetchArticles() {
        this.startLoading();
        return articlesAdapter.fetchAll()
            .then(articles => {
                this.setArticles(articles);
                return true;
            }
    }
```

Does this make sense?

**Comment by bitttttten** [comment]
Yes that is the correct idea!

I see the difference between the client use case and server use case, although that would mean I need to have a different onEnter hook for the client and server, correct?

I would like them to be the same, and I would like to not need to do something like this:

```
onEnter: (fromState, toState, routerStore) => {
    const { rootStore: { articlesStore } } = routerStore;
    const fetchInstance = articlesStore.fetchArticles();
    return IS_SERVER ? fetchInstance  : Promise.resolve();
},
```

As this doesn't scale and becomes less isomorphic. Is there a solution for this in the library already? I would imagine I could do something like (really psuedo code):

`<RouterView lazyEvaluateTransitionHooks={!IS_SERVER} />`

**Comment by nareshbhatia** [comment]
This is the best I can think of. Copying @xFloooo in case he has a better solution - he is deeper into SSR!

**Comment by xFloooo** [comment]
@bitttttten @nareshbhatia 
I think that the router should not do this... This is usually done by `apiClient`. 
[For example, how `apollo` works with `graphql`](https://github.com/apollographql/react-apollo)

**Comment by nareshbhatia** [comment]
@xFloooo, looking at the Apollo docs, it looks like they keep a flag called `ssr` (see [here](https://www.apollographql.com/docs/react/features/server-side-rendering.html#server-initialization)). This flag is used to control server side logic, e.g. [here](https://www.apollographql.com/docs/react/features/server-side-rendering.html#skip-for-ssr).

@bitttttten, I suspect you will have to do something similar. I am closing this issue for right now. Please feel free to add comments with your approach. It may help future users.

**Comment by bitttttten** [comment]
I am going to move ahead with the approach of returning in the hook or not. Thanks for the discussion!
