### ISSUE TITLE
Jest/Istanbul ignoring "ignore" hints

### ISSUE THREAD

**Issue by nareshbhatia** [nareshbhatia/mobx-state-router#4]
Would be nice to exclude conditional logging from coverage reports, but Istanbul is not cooperating. See [this](https://github.com/nareshbhatia/mobx-state-router/blob/master/src/router-store.ts#L136-L143) for an example. Also have an [open question](https://stackoverflow.com/questions/48284724/ignoring-ignore-hints) on StackOverflow. If anyone has a solution, please send a PR.

**Comment by lucianlature** [comment]
@nareshbhatia The TS compiler removes the `istanbul` comments  before executing the tests, therefore all the `ignore` flags are...well, ignored.

Simply configure `removeComments` to `false` and now the coverage is `100%`.

<pre>
{
    "compilerOptions": {
        "declaration": true,
        "declarationDir": "dist/types",
        "experimentalDecorators": true,
        "jsx": "react",
        "lib": ["es2015", "es2016", "es2017", "dom"],
        "module":"commonjs",
        "outDir": "./dist",
        "removeComments": <b>false</b>,
        "sourceMap": true,
        "strict": true,
        "target": "es5"
    },
    "include": [
        "src"
    ]
}
</pre>

**Comment by nareshbhatia** [comment]
Awesome detective work, @lucianlature! Thanks for your help.
