### ISSUE TITLE
Error handling in hooks

### ISSUE THREAD

**Issue by zeljkohuber** [nareshbhatia/mobx-state-router#40]
How should we handle custom errors that occur in any of the hooks? I could catch those errors in my own handlers but any further throwing would result in internal catch which throws 'toState is undefined'. 

Is there any option for adding onHookError callback which would be triggered when caught exception is not rejected RouterState, but some internal application error which occured in one of hooks?

Regards,

**Comment by nareshbhatia** [comment]
@zeljkohuber, can you please describe your exact use case? What is your hook trying to do? What kind of error is it throwing? If you handle it in your hook, what further errors do you have to throw? What is the desired outcome of handling the errors (e.g. show an error page)?

This will allow us to design a proper solution to your issue.

**Comment by nareshbhatia** [comment]
Also note that you can throw an instance of `RouterState` which will simple set the Router to that state.

**Comment by nareshbhatia** [comment]
Got it! I added a function `setErrorHook()` to `RouterStore`. Please let me know if this is what you are looking for.

**Comment by zeljkohuber** [comment]
That's exactly what I tought was missing. thank you a lot! BTW the package is awesome and really useful 🗡
