### ISSUE TITLE
Pass custom data within RouterState

### ISSUE THREAD

**Issue by zeljkohuber** [nareshbhatia/mobx-state-router#44]
I was wondering if `RouterState `should hold any more `data `than the one related with the URL (params, queryParam). I know that its `javascript `and I can add my own `data `property to it but what are your thoughts on that? 

For example if I want to transition to state but pass in some custom data (e.g. because I need additional state in opposed to directly navigating to that URL) within `RouterState`, would you recomend that or do it somehow else? I don't like storing that data in some store and then later clearing it out because it's not clean and safe as passing it directly with the `RouterState `.

**Comment by atifsyedali** [comment]
My 2 cents ... keep the router store pure with only route-based state.

**Comment by nareshbhatia** [comment]
@zeljkohuber, do you have a concrete example? It is hard to talk about requirements without a use case. Perhaps when we see an example we can propose a better solution.

**Comment by atifsyedali** [comment]
> Classic use case is when navigating from list to detail screen (lets say we don't have ID parameter in URL, though we mostly do, but just for the sake of this 'issue') - How would you transfer your resource ID from list to edit while navigating via router?

imo, that's not really a routing state. Seems more of a UI state. What happens when you refresh the page?

**Comment by zeljkohuber** [comment]
@atifsyedali I knew you would ask that question, that's why I said it's just an example so you can get the idea. I had similar issue which I've managed to resolve somehow (though I think it was hacky), but can't find it now to show you. Though I get your point, router state should not be concerned about that kind of state and I totally agree with you.

**Comment by nareshbhatia** [comment]
@zeljkohuber, I agree with @atifsyedali - moving from list to detail is pure UI state. It is usually kept in a store as "selectedEntity" - I would say that's the best practice.

I am closing this for now. Please feel free to leave comments.
