### ISSUE TITLE
Dev mode logging

### ISSUE THREAD

**Issue by zeljkohuber** [nareshbhatia/mobx-state-router#45]
It would be nice if there was a way of telling the `router` whether or not we want console logs in `development` mode. I've got some other plugins along with my personal loggings and its pretty hard to find anything in console full of logs.

Please let me know what you think. Thank you.

**Comment by nareshbhatia** [comment]
I realized that all that logging was for debugging purposes only. Then I read [this article](https://hackernoon.com/please-stop-using-console-log-its-broken-b5d7d396cf15) that convinced me that console.log is not a good way to debug software! It is easy enough to put breakpoints in mobx-state-router code if there is an issue. Hence I have removed all logging from the library. Enjoy the unclogged console :-).
