### ISSUE TITLE
Question on Fetching Data

### ISSUE THREAD

**Issue by geohuz** [nareshbhatia/mobx-state-router#47]
As the document stated the UI should not be responsible of fetching data, as in componentWillMount, componentDidMount, I agree with that, but there are scenarios when we need fetch data by user interaction, such as button click, I'm not sure how do we deal this in mobx-state-router, or we just use async action in mobx?

**Comment by nareshbhatia** [comment]
The button click should fire an async action in the mobx store (not in the mobx-state-router). That async action should call a service that makes the http call and returns the results which should be populated in the store. The basic pattern is that components fires actions in the store and the store calls services. Components should never call services directly.

You can see an example here:

https://github.com/nareshbhatia/mobx-shop/blob/master/src/shared/components/cart/checkout.js

Although this one does not call a service in this demo, in a real app this is where you would call a service to place an order.

Hope this helps.
