### ISSUE TITLE
Router basename setup

### ISSUE THREAD

**Issue by bpkinez** [nareshbhatia/mobx-state-router#52]
Hi Naresh,

is there any way to set basename in mobx-react-router like it is set in React Router with following:

```js
ReactDOM.render(
  <BrowserRouter basename={process.env.PUBLIC_URL}>
    <Provider {...stores}>
      <App />
    </Provider>
  </BrowserRouter>,
  document.getElementById('root')
);
```

**Comment by iexplore** [comment]
I was just looking for that same requirement.

**Comment by nareshbhatia** [comment]
This is pretty straightforward. All you need to do is to set the `basename` option when creating the history object. I created an example [here](https://github.com/nareshbhatia/mobx-state-router-examples/tree/master/relative-paths).
