### ISSUE TITLE
how to configure the routes to restrict the user to not to enter the login screen, once login is success?

### ISSUE THREAD

**Issue by 0xc0d3r** [nareshbhatia/mobx-state-router#53]
I'm setting up routes for our small react application. After login success, if we click on browser's back button then the app is redirecting to `log in` screen. How can I avoid this behavior? After logging out, I'm able to navigate to `home` screen.

TIA

**Comment by nareshbhatia** [comment]
Well, the best practice is not to mess with the browser back button. If the user clicks on the back button, they expect to see the previous screen.

If you indeed want to alter the browser's behavior, what would you want to do? You could play with the history api and wipe out the previous screen (see [this stackoverflow question](https://stackoverflow.com/questions/14437987/how-disable-browser-back-button-only-after-logout-in-mvc3-net)).
