### ISSUE TITLE
support lazy loading

### ISSUE THREAD

**Issue by pvider** [nareshbhatia/mobx-state-router#56]
Please, provide example of lazy loaded components in mobx-state-router. I have updated my React to 16.6 with Suspense and lazy, now I cannot figure out how to make `onEnter` and other Transition hooks work.
I have following `shell.js`:
```javascript
import React, { lazy, Suspense, createElement } from 'react';

import Header from './App/Header';
import Footer from './App/Footer';

const viewMap = {
    'home': lazy(() => import('./App/Home')),
    'not-found': lazy(() => import('./App/NotFound')),
    'new-task': lazy(() => import('./App/NewTask')),
.................
};

@inject('rootStore')
@observer
export default class Shell extends React.Component {
    render() {
        const { rootStore: { routerStore } } = this.props;
        const routeName = routerStore.routerState.routeName;
        const view = viewMap[routeName];
        console.log("routerState", routerStore.routerState)
        console.log("routeName", routeName)
        console.log("view", view)
        return (
            <>
                <header>
                    <Header />
                </header>
                <main>
                    <Suspense fallback={<></>}>
                        {createElement(view)}
                    </Suspense>
                </main>
                <footer>
                    <Footer />
                </footer>
            </>
        );
    }
}
```
When I don't use hooks everything works fine: I have code splitting, components are loading lazy etc.
If I use simple `onEnter` hook and return `Promise.resolve` from it, I have errors about invalid React elements because `routeName` is still `__initial__`.

**Comment by nareshbhatia** [comment]
Haven't played with suspense yet, but I will take a look.

**Comment by nareshbhatia** [comment]
See [Lazy Loading using React Suspense](https://github.com/nareshbhatia/mobx-state-router-examples/tree/master/suspense-lazy-loading). There were two key things I had to do to make the code work:

1. The pages have to export the React component as default (not as named export). This is required for the lazy loading to work.
2. You have to check if `viewMap[routeName]` returns a view. If not, then don't render anything. This will be the case with '__initial__' route.

Let me know if this works for you.

**Comment by pvider** [comment]
Thank you very much! `if (!view) return null;` helped me, now lazy loading works as it should.
