### ISSUE TITLE
RouterLink assumes that rootStore is injected

### ISSUE THREAD

**Issue by gavinbarron** [nareshbhatia/mobx-state-router#57]
If you choose to use a different approach to the configuration of the `<Provider>` then the RouterLink will fail.

For example I configure my provider using the spread operator on my root store to allow all consumers to just inject the store(s) they need and not perform any gymnastics to get the desired store. eg: `<Provider {...rootStore}>`

Then in my consuming components I can simply inject, say, routerStore.

Due to the current means of injecting rootStore using this approach renders the RouterLink Component useless as it causes MobX to crash hard. 
I realize that changing to this pattern would be a breaking change but is there another approach to injecting the routerStore in to the RouterLink that might allow for people using the spread approach on their rootStore to make use of this component?

**Comment by nareshbhatia** [comment]
Hi @gavinbarron. There is an equivalent component called `Link`, where you can inject the `RouterStore` yourself. I think that should work for you. If not, the `RouterLink` is a really simple component - take a quick look at the source and create your own that meets your requirements.

Closing for now, but feel free to leave a comment.

**Comment by nareshbhatia** [comment]
FYI, I am reconsidering the approach to require a rootStore in the Router (see https://github.com/mobxjs/mobx/issues/2354). Yes it will be a breaking change, but that can be accounted for by incrementing the major version number.

If anyone has a concern with this approach, please let me know.
