### ISSUE TITLE
Nested paths

### ISSUE THREAD

**Issue by worldbeater** [nareshbhatia/mobx-state-router#59]
Hello @nareshbhatia and thanks for your great library. Could you please provide an example on how to handle "nested" routing with `mobx-state-router`?

This works:
```js
const routes: Route[] = [{
    name: RouteNames.coolRoute,
    pattern: '/cool-route',
}]
```

This doesn't work, but I need to handle this specific route: `/cool/route`
```js
const routes: Route[] = [{
    name: RouteNames.coolRoute,
    pattern: '/cool/route' // slash instead of hyphen
}]
```

It would be great if we could document how to better handle the case defined above so other users won't face issue that I came across. Thanks in advance and thanks for your great work and support!

**Comment by nareshbhatia** [comment]
Hi @worldbeater, glad that you liked my work.

To answer your question, mobx-state-router does not support nested routes directly. However, you can easily transform any nested route into a non-nested one. Please see this comment by @davidmz who has done an implementation: https://github.com/nareshbhatia/mobx-state-router/issues/6#issuecomment-416310912.

It is probably a good idea to provide an example. I will try to add one to the companion [examples repository](https://github.com/nareshbhatia/mobx-state-router-examples) or you can beat me to it by submitting a PR :-).
