### ISSUE TITLE
Warnings when building with parcel

### ISSUE THREAD

**Issue by Regaddi** [nareshbhatia/mobx-state-router#60]
Hey,

when building a react app with parcel and mobx-state-router, it will show up some warnings:

```
⚠️  Could not load source file "../src/index.ts" in source map of "../../../node_modules/mobx-state-router/dist/index.js".
⚠️  Could not load source file "../src/index.ts" in source map of "../../../node_modules/mobx-state-router/dist/index.js".
⚠️  Could not load source file "../src/router-store.ts" in source map of "../../../node_modules/mobx-state-router/dist/router-store.js".
⚠️  Could not load source file "../../src/components/link.tsx" in source map of "../../../node_modules/mobx-state-router/dist/components/link.js".
⚠️  Could not load source file "../../src/components/router-view.tsx" in source map of "../../../node_modules/mobx-state-router/dist/components/router-view.js".
⚠️  Could not load source file "../../src/components/router-link.tsx" in source map of "../../../node_modules/mobx-state-router/dist/components/router-link.js".
⚠️  Could not load source file "../../src/adapters/static-adapter.ts" in source map of "../../../node_modules/mobx-state-router/dist/adapters/static-adapter.js".
⚠️  Could not load source file "../../src/adapters/generate-url.ts" in source map of "../../../node_modules/mobx-state-router/dist/adapters/generate-url.js".
```

By investigating the mobx-state-router folder inside of node_modules I can see that the src folder is not published:

![image](https://user-images.githubusercontent.com/1336590/53155051-86035580-35bc-11e9-8ca1-e2f66564d8c3.png)

Therefore the sourceMap can't resolve the paths to the source files.

**Comment by nareshbhatia** [comment]
That's a good observation @Regaddi. Would be great to get this working, but I may need some help.

Just as a quick experiment, I went to the mobx-shop example and copied the sources to the mobx-state-router bundle under node_modules:

![image](https://user-images.githubusercontent.com/1220198/53173273-569d1a80-35b5-11e9-80aa-781e0f3fa3c5.png)

However, when I try to look at the source in Chrome debugger, I am not able to do it. It only shows the compiles JavaScript source:

![image](https://user-images.githubusercontent.com/1220198/53173390-93691180-35b5-11e9-8b3a-e184d2aaa528.png)

I even tried to step into mobx-state-router code and it is still showing the JavaScript file and not the TypeScript source. What am I missing?

**Comment by Regaddi** [comment]
Hey @nareshbhatia,

I think it should be fine if you add the src folder to the published files in your package.json:

https://github.com/nareshbhatia/mobx-state-router/blob/master/package.json#L19

Chrome DevTools is probably a completely different story 😄

**Comment by nareshbhatia** [comment]
Yes, that can be easily done. I was just wondering how can we benefit from it. I am sure this problem has been solved - just a matter of Googling :-).

I will work on it. Need to updated dependencies anyway!

**Comment by nareshbhatia** [comment]
Done. Please let me know how parcel feels about this release :-)

**Comment by Regaddi** [comment]
🎉You're awesome, @nareshbhatia! Warnings are gone after updating to 4.0.4 😄

**Comment by nareshbhatia** [comment]
Glad to help!
