### ISSUE TITLE
Incorrect peer dependency

### ISSUE THREAD

**Issue by eDubrovsky** [nareshbhatia/mobx-state-router#62]
Hi! When I create Docker, i see this warning message:

`warning " > mobx-state-router@4.0.4" has incorrect peer dependency "mobx@^4.x".`

I use:
```
  "mobx": "^5.9.0",
  "mobx-react": "^5.4.3",
  "mobx-state-router": "^4.0.4",
```

**Comment by nareshbhatia** [comment]
Done. Please try with version 4.0.5.

**Comment by eDubrovsky** [comment]
It' work, thanks!
