### ISSUE TITLE
pass custom parameters through router state

### ISSUE THREAD

**Issue by JosipTomaic** [nareshbhatia/mobx-state-router#70]
How I can pass custom parameter through router state but I don't want that custom parameters to be seen in route?
Is this even possible using this package?
The application is made in Reactjs

The scenario si:
1. click on button and then call goTo method from router store
2. in that goTo method call pass parameter from component
3. read that passed parameter and print it on screen

Any help or advice would be appreciated.
Thanks in advance.

**Comment by nareshbhatia** [comment]
This should be possible in the upcoming 5.x release. You can pass any number of options into RouterState (and also RouterStore). See [here](https://github.com/nareshbhatia/mobx-state-router/blob/master/src/stores/RouterState.ts#L43-L46). Please let me know if this is what you had in mind.

**Comment by nareshbhatia** [comment]
Closing for now. Please feel free to add comments.
