### ISSUE TITLE
encode / decode of params

### ISSUE THREAD

**Issue by UweWindt** [nareshbhatia/mobx-state-router#72]
When i call a route by routerStore.goTo with:

 `params={ aparam : "xx & xx"}`

i will get in the onEnter callback:

`toState.params={ aparam : "xx %26 xx"}`

It seems encoding / decoding is not working symetric, at least not for '&'

**Comment by nareshbhatia** [comment]
Hi @UweWindt, is this a single param that happens to have a `&` inside it or two params? I have never tested with params that have spaces or special characters in them. What is your actual use case?

**Comment by UweWindt** [comment]
Hi @nareshbhatia ,
it's one parameter.

"Normal" ascii characters are not the problem.
For German "Umlaute" like "ä,ö,ü" etc.  i can use encodeURIComponent / decodeURIComponent to stay symetric.
But the "&" is resilient.

By the way: Congrates to mobx-state-router. It's a super libray. 

Uwe

**Comment by nareshbhatia** [comment]
Thanks @UweWindt, glad you like my work. I just released version 5 this morning, you will love it even more! I have simplified the APIs and made them more flexible. For example, you can now pass options into `RouterStore` and `RouterState`. Please see the change log [here](https://github.com/nareshbhatia/mobx-state-router/blob/master/CHANGELOG.md) and the new [docs site](https://nareshbhatia.github.io/mobx-state-router/)

Perhaps you could suggest where I should do the encoding/decoding (or even a PR?). We will have to make sure that no tests break + add tests for this new feature.

**Comment by UweWindt** [comment]
Hi @nareshbhatia ,

i seems that the German Umlaute now working out of the box. Maybe it has to do with a new version of history, that was released meanwhile.

The workaround for '&' i use is:

@action.bound
    async onEnter(fromState: RouterState, toState: RouterState) {
     const params=decodeParams(toState.params);
    ....
}

with  decodeParams as:

export const decodeParams = (params: any) => {
    if (params) {
        let rv = R.clone(params);  // R is Ramda. I don't know if  this is essential necessary. 
        Object.keys(rv)
            .forEach(p => rv[p] = decodeURIComponent(rv[p]));
        return rv;
    }
    return {};
};

Maybe it helps.

Next week i'm busy with my project. But i will try out v5 soon. The breaking changes seams to be managable.
Thank you in advance

**Comment by nareshbhatia** [comment]
Closing this for now. Please reopen if still a problem.
