### ISSUE TITLE
SSR approach (+ thanks!)

### ISSUE THREAD

**Issue by thirdman** [nareshbhatia/mobx-state-router#73]
### Thanks!
Firstly, thanks heaps! I've used this on a couple of  side projects, and really appreciate your work - it hits a sweet spot for simplicity and speed to get working.

### SSR
Is there a suggested approach to using this server side? (In my case with create-react-app). I didn't see anything in documentation, so thought I'd ask. 

😃

**Comment by nareshbhatia** [comment]
@thirdman, glad you liked it. For SSR you can look at the examples project: https://github.com/nareshbhatia/mobx-state-router-examples/tree/master/ssr

**Comment by thirdman** [comment]
OMG sorry, how did I not see that.
