### ISSUE TITLE
Question: Bypassing HistoryAdapter

### ISSUE THREAD

**Issue by evanblack** [nareshbhatia/mobx-state-router#8]
I had a quick question. Lets say I'm not interested in modifying/tracking the browser address bar while navigating through my app. Would I just need to write my own (simpler) `HistoryAdapter`, or do I bypass it altogether by directly modifying the `routerStore`?

**Comment by nareshbhatia** [comment]
You can bypass `HistoryAdapter` completely! As shown in the architecture diagram, `HistoryAdapter` and `RouterView` are both watching the `RouterState` - they are dependent on it. However there is no reverse dependency from `RouterState` to anything! It's a standalone state machine. TL;DR - just delete [these two lines](https://github.com/nareshbhatia/mobx-shop/blob/master/src/app.js#L38-L39) in your app and `HistoryAdapter` is gone.

**Comment by nareshbhatia** [comment]
@evanblack, if you are bypassing the `HistoryAdapter`, you will have to initialize the RouterState to a known state yourself, e.g.:

    rootStore.routerStore.goTo(new RouterState('home'));

**Comment by evanblack** [comment]
Thanks! Library looks great. I’m looking forward to giving it a try!
