### ISSUE TITLE
Expected "param" to be a string

### ISSUE THREAD

**Issue by Yuniverse-tech** [nareshbhatia/mobx-state-router#81]
Uncaught TypeError: Expected "locale" to be a string

const Routes: Route[] = [
	{
		name: "home",
		pattern: "/:locale"
	}, 
	{
		name: "services",
		pattern: "/:locale/services"
	},
...

The **: locale ** parameter represents "en" or "fr" and is always a string. All other parameters defined in this form do not work and return the same error "to be string". Has anyone already been confused about this problem?

When I do it this way: pattern: "/: locale?", I've not error but locale parameter is not recognized and does not appear in url.

**Comment by nareshbhatia** [comment]
Hi @Yuniverse-tech, I don't see any problems as such - this should work. Have you looked at the example apps? Here's [one example](https://github.com/nareshbhatia/mobx-state-router/blob/master/examples/mobx-shop/src/stores/routes.ts#L47).

If not create a minimal app where this issue can be reproduced and post it here.

**Comment by Yuniverse-tech** [comment]
I think it's related to my development environment. Regards.
