### ISSUE TITLE
beforeEnter hook  started twice when a parameter is numeric

### ISSUE THREAD

**Issue by leoperria** [nareshbhatia/mobx-state-router#88]
Hi, first of all thanks @nareshbhatia for this great project ! I'm starting to use mobx-state-router so maybe this is  red herring. I had  the exact same problem of @lukavuletic in #71, basically I was using this link component:

```typescript
<RouterLink routeName="folder" params={{ folderId: 1 }} />   // <--- NOTE: folderId  is a number and not a string
```
and this was triggering the double transitions. So  I tried to debug those state transitions in `beforeEnter` hook and I noticed that when I clicked the link the hook was  called twice. The first time with `folderId`  as the number 1 and the second time as the string "1".

So I tried this way:

```typescript
<RouterLink routeName="folder" params={{ folderId: "1" }} />   // <--- NOTE: this time folderId  is a string
```

and the problem disappeared. Is this the same problem as #58 ? Could it be a good idea to runtime check if `typeof param` is `string` to avoid this ?

thanks for your help

**Comment by nareshbhatia** [comment]
Thanks, @leoperria. I am glad that mobx-state-router is working well for you.

The router internals assume that the window location is a string and all params/queryParams are strings. Also the dependent libraries used for parsing and URL generation make the same assumptions. Touching this logic would mean introducing unintentional bugs.

My suggestion would be to avoid using numbers as parameters. Even if you must, do a conversion to/from string at the application level. I think that is the safest approach. If the number is an object id, consider using uuids - most databases do that these days anyway. It is also more secure as your users can't guess what the other object ids are.

Closing this for now. Please reopen if this needs to be discussed further.

**Comment by leoperria** [comment]
Thanks for clarifying, I will find a way around this at application level
