### ISSUE TITLE
Transition Hooks 

### ISSUE THREAD

**Issue by aap82** [nareshbhatia/mobx-state-router#9]
I've played around with the library a bit, and if welcomed, a few observations/suggestions.  First, regarding the transition hooks such as 
```

onEnter: (fromState, toState, routerStore) => {
        const { rootStore: { itemStore } } = routerStore;
        itemStore.loadDepartmentItems(toState.params.id);
        return Promise.resolve({ fromState, toState });
    }
```
Since `RouterState` has only read-only properties, is there a reason that `fromState` and `toState` should be resolved from the hook?  Wouldn't it be safer not to resolve them, thereby eliminating any possibility of transitioning to another state than the one intended?

Along with this, I think the transition hook promise chain could be implemented alternatively as (written in CS, but should be straightforward):
```

{ beforeExit, onExit } = this.getRoute(fromState.routeName)
{ beforeEnter, onEnter } = this.getRoute(toState.routeName)
[ beforeExit, beforeEnter, onExit, onEnter ].reduce(
  (promise, hook) =>
      return promise unless hook
      return promise.then(=>  return hook(fromState, toState, this))
  , Promise.resolve() 
)
.then =>             this.setRouterState(toState);    return toState
.catch (errState) => this.setRouterState(errState);   return errState
 ```
I haven't tested this, but it is functionally equivalent, and imho, much cleaner.

**Comment by nareshbhatia** [comment]
@aap82, thanks for the observations/suggestions - these are always welcome.

> Since RouterState has only read-only properties, is there a reason that fromState and toState should be resolved from the hook? Wouldn't it be safer not to resolve them, thereby eliminating any possibility of transitioning to another state than the one intended?

While RouterState itself has read-only properties, it is fully intended that hooks can change the transition by returning a completely new `toState`. You can see a use case [here](https://github.com/nareshbhatia/mobx-state-router#redirecting-to-the-sign-in-page).

I like your simplification of the promise chain. Nice pattern! Will implement.

**Comment by aap82** [comment]
I think you missed my point, but at the same time you're example makes my point very clear:   a **rejected** promise results in a different toState, _not_ a **resolved** one.  And if you notice in the promise chain example above, that's taken into account.

**Comment by nareshbhatia** [comment]
Yep, definitely missed your point :-). Reworking the logic.

**Comment by aap82** [comment]
No problem.  It makes sense, right?

Also, (and feel free to fully disregard this):
IMO, hooks are more useful when implemented as composed functions (just like router5¸ but I'll take it a step further).  

Especially if you're leveraging idiomatic programming styles, then simple functions such as the one below can become quite reusable.

```
onEnterRoute = ({ rootStore }, routeName) => (toState, fromState) =>
  rootStore.getStore(routeName).fetchItem(toState.params.id)
  .then () =>  return Promise.resolve()
  .catch (err) =>
      rootStore.viewStore.showNotification(err.msg)
      return Promise.reject(fromState)
  
```
It's just something to think about.

**Comment by nareshbhatia** [comment]
@aap82, I reworked the processing of transition hooks as you suggested. Please see the [promise-chain](https://github.com/nareshbhatia/mobx-state-router/tree/promise-chain) branch. If all looks ok, I will merge to master.

Your suggestion to implement hooks as composed functions also looks good, however is that a change in mobx-state-router API or just a suggestion for people writing transition hooks?

**Comment by aap82** [comment]
BTW, i forgot to mention, I"m not a programmer at all by trade, with no formal training, so you don't want to rely on me for code review.  But it looks fine to me.  :)   

As for the composed function hooks, I simply mentioned it to you as something to think about if you wanted to extend the functionality.  Food for thought.

**Comment by nareshbhatia** [comment]
Well, that's pretty good for not being a programmer by trade :-). Thanks for reviewing. Will be merging to master after changing docs, examples etc.

**Comment by aap82** [comment]
Did you confirm it works?  I might be mistaken, but i thot you have to explicity use return in reduce, as well as the nested promise.

**Comment by nareshbhatia** [comment]
Where do you think I am missing a return: [router-store.ts](https://github.com/nareshbhatia/mobx-state-router/blob/master/src/router-store.ts#L165-L190)? What line number?

It seems to be working perfectly. Test suite is passing, mobx-shop is working correctly.

**Comment by aap82** [comment]
170-171 but if its working, great!

**Comment by nareshbhatia** [comment]
So in ES6/TS, the `=>` without a `{ }` means a returned value. So we should be fine!
