### ISSUE TITLE
Support mobx-react-lite as well as mobx-react

### ISSUE THREAD

**Issue by coxm** [nareshbhatia/mobx-state-router#92]
Currently `observer` is imported from mobx-react but only used for functional components ([RouterView](https://github.com/nareshbhatia/mobx-state-router/blob/master/src/components/RouterView.tsx) and [RouterLink](https://github.com/nareshbhatia/mobx-state-router/blob/master/src/components/RouterLink.tsx),), so it should be possible to use [mobx-react-lite](https://github.com/mobxjs/mobx-react-lite) instead.

mobx >= 6 includes mobx-react-lite as a dependency and uses the mobx-react-lite `observer` [internally](https://github.com/mobxjs/mobx-react/blob/master/src/observer.tsx) (calling the mobx-react-lite version for function components), so changing the imports to use mobx-react-lite would not affect this library's operation.

Simply changing the `import` statements _would_ affect those users of this library still depending on mobx 5, though.

Perhaps there's a better solution, though at present I can only think of kludges like providing an alternative build.

**Comment by nareshbhatia** [comment]
@coxm, thanks for the suggestion. As you mention, it will affect users depending on mobx 5. What is your motivation for importing from mobx-react-lite directly? Are you only depending on that package?

**Comment by nareshbhatia** [comment]
@coxm, released v6.0.0-beta.1 with @next tag. The new dependencies are mobx v6 and mobx-react-lite v3  Please let me know if this version works for you.
