### ISSUE TITLE
Support MobX v6

### ISSUE THREAD

**Issue by kirilldronkin** [nareshbhatia/mobx-state-router#95]
Hi, in v6 `decorate` utility is no longer available and `makeObservable` should be used instead.

**Comment by nareshbhatia** [comment]
Released v6.0.0-beta.1 with @next tag. The new dependencies are mobx v6 and mobx-react-lite v3  Please let me know if this version works for you.

**Comment by kirilldronkin** [comment]
The migration of my project is planned on the next week, so if someone can check it before me I'll be very appreciate.

**Comment by nareshbhatia** [comment]
No worries.

**Comment by jmampost** [comment]
Been using beta.1 on my project for a few days now, no issues so far. Thanks for this wonderful library 👍

**Comment by nareshbhatia** [comment]
Thanks @jmampost. Glad you like the library.

There is one PR pending for upgrade to latest version of history. As soon as I get a chance I want to review/merge it, then final v6!!!
