### ISSUE TITLE
Attempted import error: 'decorate' is not exported from 'mobx'

### ISSUE THREAD

**Issue by iexplore** [nareshbhatia/mobx-state-router#98]
After upgrading to Mobx@6.0.3 running the project fails compiling with
 "./node_modules/mobx-state-router/dist/mobx-state-router.esm.js"
 "Attempted import error: 'decorate' is not exported from 'mobx'."

**Comment by nareshbhatia** [comment]
Please use `mobx-state-router@6.0.0-beta.1` (same as `mobx-state-router@next`)

**Comment by iexplore** [comment]
Sorry missed [Support MobX v6 #95](https://github.com/nareshbhatia/mobx-state-router/issues/95)
